export const pizzaDatas = [
  {
    id: "1",
    img: "/image/pizza1.png",
    name: "CAMPAGNOLA",
    price: 19.9,
    desc: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock",
  },
  {
    id: "2",
    img: "/image/pizza1.png",
    name: "CAMPAGNOLA",
    price: 22.5,
    desc: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock",
  },
  {
    id: "3",
    img: "/image/pizza1.png",
    name: "CAMPAGNOLA",
    price: 25,
    desc: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock",
  },
  {
    id: "4",
    img: "/image/pizza1.png",
    name: "CAMPAGNOLA",
    price: 19.9,
    desc: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock",
  },
  {
    id: "5",
    img: "/image/pizza1.png",
    name: "CAMPAGNOLA",
    price: 19,
    desc: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock",
  },
  {
    id: "6",
    img: "/image/pizza1.png",
    name: "CAMPAGNOLA",
    price: 18,
    desc: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock",
  },
  {
    id: "7",
    img: "/image/pizza1.png",
    name: "CAMPAGNOLA",
    price: 15,
    desc: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock",
  },
  {
    id: "8",
    img: "/image/pizza1.png",
    name: "CAMPAGNOLA",
    price: 20,
    desc: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock",
  },
];
